apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
spec:
  selector:
    app: {{ .Values.app.name }}-frontend
  ports:
    - protocol: TCP
      port: 3000
      #targetPort: 3000