apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-frontend
spec:
  selector:
    app: {{ .Values.app.name }}-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80