apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /web
        backend:
          serviceName: {{ .Values.app.name }}-frontend
          servicePort: 3000
      - path: /api
        backend:
          serviceName: {{ .Values.app.name }}-backend
          servicePort: 8000