app:
  name: "test-app"

frontend:
  replicas: "1"
  image: "kennedyuche/frontend-web"
  tag: "latest"
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: ""
      cpu: ""

backend:
  replicas: "1"
  image: "kennedyuche/backend-api"
  tag: "latest"
  resources:
    requests:
      memory: "50Mi"
      cpu: "20m"
    limits:
      memory: ""
      cpu: ""